version: "3"
services:
  database:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - "convomarkbot_db:/var/lib/postgresql/data"
  redis:
    image: redis:5
    ports:
    - "6379:6379"

volumes:
  convomarkbot_db:
