[build]
base = "frontend"
command = "yarn install && yarn build"
publish = "frontend/dist"

[context.production]
  [context.production.environment]
    VUE_APP_TELEGRAM_BOT_NAME = "convomarkbot"

[context.develop]
  [context.develop.environment]
    VUE_APP_TELEGRAM_BOT_NAME = "convomarkstagingbot"
    VUE_APP_API_ENDPOINT = "https://convomark-staging.server.matteojoliveau.com"