version: 2.1
jobs:
  test_backend:
    docker:
      - image: circleci/node:10.15
        environment:
          NODE_ENV: test
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-{{ checksum "backend/yarn.lock" }}
            - yarn-
      - run:
          name: Yarn install
          command: yarn --cwd backend install --cache-folder ~/.cache/backend/yarn
      - save_cache:
          name: Save Yarn cache
          key: yarn-{{ checksum "backend/yarn.lock" }}
          paths:
            - ~/.cache/backend/yarn

      - run:
          name: Run tests
          command: yarn --cwd backend test

  build_and_deploy:
    docker:
      - image: matteojoliveau/circleci-kube-deployer:latest
        environment:
          NODE_ENV: production

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Authenticate Kubernetes
          command: .circleci/setup-kube-auth

      - run:
          name: Deploy on Kubernetes
          command: |
            case "$CIRCLE_BRANCH" in
              develop) profile=staging ;;
              master) profile=production ;;
              *) exit 1 ;;
            esac
            cd backend
            kubectl config use-context $profile
            skaffold run -p $profile

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - build_and_deploy:
          requires:
            - test_backend
          filters:
            branches:
              only:
                - develop
                - master
